# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5ea3e881fa9eded6c91926e446c31e47aa56384dab04ff3493c46fb27f7a9e106997b18c076cd98f0d1fea61fac6e56f3a9c4e6d433de5cbaf00b04977f047

test:
  secret_key_base: 51c13c763a873e50b5344da29e5da3d635241e81fd54f3f6a1793d8915a3a3a986d28c2c627857087f6f93e84a603c8069852e68b98f2fcad08ac58476869177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
